import { jsPDF } from "jspdf";
import QRCode from "qrcode";
const company="Summit Roofing Co", city="Austin";
const qr = await QRCode.toDataURL("https://x/?lead=1",{margin:1,width:600});
const doc=new jsPDF({unit:"in",format:"letter"});
const pageW=8.5,half=pageW/2;
const BLUE=[30,79,255],GREEN=[16,185,129],INK=[17,24,39];
doc.setDrawColor(190);doc.setLineDashPattern([0.08,0.08],0);doc.line(half,0,half,11);doc.setLineDashPattern([],0);
const drawHanger=(offsetX)=>{const pad=0.28,x=offsetX+pad,w=half-pad*2,cx=offsetX+half/2;
doc.setDrawColor(225);doc.setLineWidth(0.012);doc.roundedRect(x,0.3,w,10.4,0.18,0.18,"S");
doc.setFillColor(245,246,248);doc.setDrawColor(205);doc.circle(cx,1.0,0.42,"FD");doc.setFillColor(255,255,255);doc.circle(cx,1.0,0.32,"F");
doc.setFillColor(245,246,248);doc.roundedRect(cx-0.09,0.42,0.18,0.5,0.09,0.09,"F");
const headTop=1.7,headH=2.5;doc.setFillColor(...BLUE);doc.roundedRect(x,headTop,w,headH,0.14,0.14,"F");
doc.setFont("helvetica","bold");doc.setTextColor(255,255,255);doc.setFontSize(11);doc.text("YOUR NEIGHBORHOOD CREW",cx,headTop+0.5,{align:"center",charSpace:0.02});
doc.setFontSize(30);doc.text(company,cx,headTop+1.35,{align:"center",maxWidth:w-0.5});
doc.setFillColor(...GREEN);doc.roundedRect(cx-0.7,headTop+1.7,1.4,0.07,0.035,0.035,"F");
doc.setFont("helvetica","normal");doc.setFontSize(11);doc.text("Trusted local service",cx,headTop+2.15,{align:"center"});
const midY=headTop+headH+0.7;doc.setFont("helvetica","normal");doc.setFontSize(13);doc.setTextColor(...INK);doc.text("We are doing some work in",cx,midY,{align:"center"});
doc.setFont("helvetica","bold");doc.setFontSize(24);doc.setTextColor(...BLUE);doc.text(city+" today!",cx,midY+0.55,{align:"center",maxWidth:w-0.4});
doc.setFont("helvetica","normal");doc.setFontSize(11.5);doc.setTextColor(80,88,100);doc.text("While our team is in the area, get a fast, free quote — no obligation.",cx,midY+1.15,{align:"center",maxWidth:w-0.5});
const footH=2.7,footTop=10.7-footH;doc.setFillColor(...GREEN);doc.roundedRect(x,footTop,w,footH,0.14,0.14,"F");
doc.setFont("helvetica","bold");doc.setTextColor(255,255,255);doc.setFontSize(15);doc.text("Scan to get a",cx,footTop+0.5,{align:"center"});doc.text("fast, free quote",cx,footTop+0.85,{align:"center"});
const qrSize=1.25,tile=qrSize+0.2;doc.setFillColor(255,255,255);doc.roundedRect(cx-tile/2,footTop+1.05,tile,tile,0.1,0.1,"F");doc.addImage(qr,"PNG",cx-qrSize/2,footTop+1.15,qrSize,qrSize);
doc.setFont("helvetica","normal");doc.setFontSize(9.5);doc.setTextColor(255,255,255);doc.text("Powered by Van AI",cx,footTop+footH-0.22,{align:"center"});};
drawHanger(0);drawHanger(half);
import fs from "fs";fs.writeFileSync("/tmp/test.pdf",Buffer.from(doc.output("arraybuffer")));
console.log("ok");
